import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

// Clean up old caches
cleanupOutdatedCaches()

// Retrieve Firebase Messaging object
importScripts('https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js')
importScripts('https://www.gstatic.com/firebasejs/8.10.1/firebase-messaging.js')

// Config is compiled directly into the Service Worker at build time
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID
}

// Only initialize if we have the config
if (firebaseConfig.apiKey && !firebase.apps.length) {
  firebase.initializeApp(firebaseConfig)
  const messaging = firebase.messaging()

  // Background message handler
  messaging.onBackgroundMessage((payload) => {
    console.log('[sw.js] Received background message ', payload)

    // If the payload already contains a notification, the browser automatically displays it.
    // We must return early to avoid displaying a duplicate notification.
    if (payload.notification) {
      console.log('[sw.js] Notification already handled automatically by browser.')
      return
    }

    const notificationTitle = payload.data?.title || 'YuiChat'
    const notificationOptions = {
      body: payload.data?.body || 'Bạn có tin nhắn mới.',
      icon: '/pwa-192x192.png',
      badge: '/favicon.ico',
      data: {
        url: payload.data?.conversation_id ? `/chat/${payload.data.conversation_id}` : '/'
      }
    }

    self.registration.showNotification(notificationTitle, notificationOptions)
  })
}

// Notification click handler
self.addEventListener('notificationclick', function (event) {
  event.notification.close()
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function (clientList) {
      const targetUrl = event.notification.data.url
      // If window is already open, focus it and navigate
      for (let i = 0; i < clientList.length; i++) {
        let client = clientList[i]
        if (client.url.includes(self.registration.scope) && 'focus' in client) {
          client.navigate(targetUrl)
          return client.focus()
        }
      }
      // If window is not open, open a new one
      if (clients.openWindow) {
        return clients.openWindow(targetUrl)
      }
    })
  )
})

// Skip waiting and claim clients so that new SW takes control immediately
self.addEventListener('install', () => self.skipWaiting())
self.addEventListener('activate', (event) => event.waitUntil(clients.claim()))
